from milcapy import SystemModel

model = SystemModel()
model.add_material("concreto", 2.2*10**7, 0.3)
model.add_rectangular_section("sec1", "concreto", 0.3, 0.4)
model.add_rectangular_section("sec2", "concreto", 0.3, 0.5)
model.add_node(1, 0, 1.2)
model.add_node(2, 0, 4.7)
model.add_node(3, 6, 4.7)
model.add_node(4, 6, 0.0)
model.add_member(1, 1, 2, "sec1")
model.add_member(2, 2, 3, "sec2")
model.add_member(3, 4, 3, "sec1")
model.add_restraint(1, *(True, True, True))
model.add_restraint(4, *(True, False, False))
model.add_elastic_support(4, ky=800, krz=200)
model.add_elastic_support(3, krz=100)
model.add_load_pattern("dead")
model.add_distributed_load(1, "dead", 0, -15)
model.add_distributed_load(2, "dead", 0, -20)
model.add_load_pattern("dead2")
model.add_point_load(2, "dead2", fx=20)
model.add_point_load(3, "dead2", fx=-20, fy=-10)
model.add_end_length_offset(2, 0.5, 0.5, False, False, 0.5, 0.5)
model.add_prescribed_dof(2, "dead", ux=0.5, uy=0.5, rz=3.1415*1/180)
model.add_point_load(3, "dead", 0, fy=-15)
model.add_load_pattern("wind")
model.add_point_load(3, "wind", fx=-15)
model.add_load_pattern("earthquake")
model.add_point_load(3, "earthquake", fx=15, fy=15)
model.solve()
model.plotter_options.mod_krz_rotation_angle = 180
model.plotter_options.mod_scale_point_load = 1
# model.show()
model.plot_model('wind')